### ISSUE TITLE
Chrome Custom Tab not working

### ISSUE THREAD

**Issue by callingmedic911** [braintree/braintree-android-drop-in#101]
### General information

* SDK/Library version: 3.7.0
* Environment: Sandbox
* Android Version and Device: OnePlus One with Android 7.1.1

### Issue description

Whenever I try to transact using PayPal there is no in-app browser behaviour of Chrome Custom Tabs. It opens the separate app to complete the transaction.
I see following in log:
```
2018-10-30 16:01:25.466 1309-2494/? W/ActivityManager: Unable to start service Intent { act=androidx.browser.customtabs.action.CustomTabsService pkg=com.android.chrome } U=0: not found
2018-10-30 16:01:25.467 1309-20967/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@49b9531
2018-10-30 16:01:25.483 1309-20484/? W/ActivityManager: Unable to start service Intent { act=androidx.browser.customtabs.action.CustomTabsService pkg=com.android.chrome } U=0: not found
2018-10-30 16:01:25.484 1309-4221/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@299a416
2018-10-30 16:01:25.486 1309-21009/? W/ActivityManager: Unable to start service Intent { act=androidx.browser.customtabs.action.CustomTabsService pkg=com.android.chrome } U=0: not found
2018-10-30 16:01:25.487 1309-2865/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@a6dc197
2018-10-30 16:01:25.513 1309-20950/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://checkout.paypal.com/... flg=0x10000000 pkg=com.android.chrome cmp=com.android.chrome/com.google.android.apps.chrome.IntentDispatcher} from uid 10264 on display 0
2018-10-30 16:01:25.552 1309-20483/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://checkout.paypal.com/... flg=0x14002000 pkg=com.android.chrome cmp=com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity (has extras)} from uid 10083 on display 0
2018-10-30 16:01:25.685 1309-21009/? I/ActivityManager: Start proc 22120:com.android.chrome:sandboxed_process17/u0i89 for service com.android.chrome/org.chromium.content.app.SandboxedProcessService17
```

I suspect the issue is something because I'm using androidx.

**Comment by quinnjn** [comment]
This is an issue with the androidx conversion. [browser-switch hardcodes the custom tabs intent](https://github.com/braintree/browser-switch-android/blob/fa4bf9d8fb9688110196c37b6db8b6949aa2a282/browser-switch/src/main/java/com/braintreepayments/browserswitch/ChromeCustomTabs.java#L29-L30). It looks like other libraries have had this issue as well: https://github.com/openid/AppAuth-Android/commit/bfe9047788ceff0a6325959b0fc7ba5c2c5ea1d6. 

We'll fix this up in a hotfix release. Thank you for letting us know!

**Comment by quinnjn** [comment]
@callingmedic911 We released [3.7.1](https://github.com/braintree/braintree-android-drop-in/releases/tag/3.7.1) which includes the fix accessing Chrome Custom Tabs when using Jetifier

**Comment by callingmedic911** [comment]
@quinnjn I tried 3.7.1 but unfortunately, the problem is still there. I checked log and it is still trying to find
```
androidx.browser.customtabs.action.CustomTabsService
```
This seems to be issue with Jetifier that is replacing string 
```
public static final String ACTION_CUSTOM_TABS_CONNECTION =
            "android.support.customtabs.action.CustomTabsService";
```
to incorrect androidx pacakage name.

I checked [here](https://github.com/openid/AppAuth-Android/issues/395), proposed fix is a [hack using StringBuilder](https://github.com/DreaminginCodeZH/CustomTabsHelper/blob/master/library/src/main/java/org/chromium/customtabsclient/CustomTabsHelper.java#L44) but there doesn't seem to be another way for now.

**Comment by ksuralta** [comment]
@quinnjn : I got an update from my merchant that the issue is still reproducible with this version of the SDK.  Can we re-open this issue?

**Comment by quinnjn** [comment]
We updated browser-switch-android removing the hardcoded string in favor of the import: https://github.com/braintree/browser-switch-android/commit/09912eff9e4872a8f4cb809a047c92717acf52fe

That went out as browser-switch 0.1.7, and the dependency chain should look something like this:
```
braintree-android-drop-in:3.7.1
+ braintree:2.18.1
  + browser-switch:0.1.7
```

**Comment by quinnjn** [comment]
@callingmedic911 I did a quick demo of braintree-android-drop-in @ 3.7.1 and didn't have any issues with PayPal tokenization using AndroidX.

You can find the demo here: https://github.com/quinnjn/braintree-android-drop-in-paypal-androidx

Let us know if there is anything different between this integration and yours.

**Comment by callingmedic911** [comment]
@quinnjn I cloned your sample repo and ran on Pixel 2 Emulator with Pie and I still can see Chrome opens separately with following in log:
```
Unable to start service Intent { act=androidx.browser.customtabs.action.CustomTabsService pkg=com.android.chrome } U=0: not found
```

I guess some difference in build config? Just to be sure, I removed all versions of Build Tools except 28.0.3.
and, I'm using Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14

This is a really annoying bug. 
If you require any more info, let me know

**Comment by callingmedic911** [comment]
> We updated browser-switch-android removing the hardcoded string in favor of the import: [braintree/browser-switch-android@09912ef](https://github.com/braintree/browser-switch-android/commit/09912eff9e4872a8f4cb809a047c92717acf52fe)
> 
> That went out as browser-switch 0.1.7, and the dependency chain should look something like this:
> 
> ```
> braintree-android-drop-in:3.7.1
> + braintree:2.18.1
>   + browser-switch:0.1.7
> ```

Yes, I figured dependency tree and commit and was surprised bug is still there. That's why I linked [DreaminginCodeZH/CustomTabsHelper/issues/5](https://github.com/DreaminginCodeZH/CustomTabsHelper/issues/5), where developer also tried using lib constants like CustomTabsService.ACTION_CUSTOM_TABS_CONNECTION but Jetifier still rename to the incorrect androidx package name.

**Comment by callingmedic911** [comment]
Here's the issue on Issue Tracker: https://issuetracker.google.com/issues/119183822

**Comment by quinnjn** [comment]
@callingmedic911 thanks for opening that issue. I traced through it sounds addressed for Android Studio 3.3. 

I downloaded 3.3 RC2 today, and the built braintree-android Demo. The Demo was able to tokenize PayPal in a Chrome Custom Tab on a Nexus 5X emulator.

**Comment by callingmedic911** [comment]
I waited and used stable 3.3 but issue still persists. Looking at reported Google issue, it is [commented](https://issuetracker.google.com/issues/119183822#comment7) it'll be resolved in beta03 of Jetifier processor, that is yet to be released.

Here is proposed fix when beta03 of Jetifier processor is released.
```
buildscript {
   dependencies {
       classpath 'com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta03'
   }
}
```
