### ISSUE TITLE
ERROR: Failed to resolve: org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.1.4-1

### ISSUE THREAD

**Issue by gevgha** [braintree/braintree-android-drop-in#155]
targetSdkVersion 29
compileSdkVersion 29compileSdkVersion 29
minSdkVersion 21

**Comment by gevgha** [comment]
implementation 'com.braintreepayments.api:drop-in:4.3.1'

**Comment by Epreuve** [comment]
Hey @gevgha You will need to add the repository for the Cardinal SDK to your `build.gradle` as outlined [here in our docs](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3#generate-a-client-token).  This should fix the dependency resolution error you're getting.

**Comment by gevgha** [comment]
Thank you , But there is still a problem, Manifest merger failed with
multiple errors, see logs, You can send a example project

пт, 6 сент. 2019 г. в 18:52, Tim M <notifications@github.com>:
