### ISSUE TITLE
Nonce is already 3D Secure

### ISSUE THREAD

**Issue by danielebart** [braintree/braintree-android-drop-in#165]
### General information

* SDK/Library version: 4.4.1
* Environment: Sandbox and Production

### Issue description

The result of the `DropInActivity` is ` ErrorWithResponse (422): Nonce is already 3D Secure` when the activity is destroyed. 

Steps to Reproduce:
- Enable `Don't keep activities` in the Android Dev Menu.
- Perform a payment with a payment method which requires a 3D Secure verification.
- Complete the 3DS verification.
- The result from the DropInActivity in the `onActivityResult` is `ErrorWithResponse (422): Nonce is already 3D Secure`.

This is an old related issue in the braintree_android repo: https://github.com/braintree/braintree_android/issues/181 

I was able to reproduce this **also** on the Demo app in the repo

![Screenshot_1575384256](https://user-images.githubusercontent.com/15895153/70061147-1064f500-15e4-11ea-8b96-88f4e04790f1.png)

**Comment by danielebart** [comment]
After digging a bit into the `Dropin` code, it's quite clear that `ThreeDSecure#performVerification` it's called twice after retuning from the 3DSecure verification when the `DropInActivity` is destroyed.

**Comment by sestevens** [comment]
@danielebart Thanks for opening this issue. We'll take a closer look and post updates here.

**Comment by sarahkoop** [comment]
Hi @danielebart - We've released version `6.0.0-beta2` of the Drop-in SDK that should resolve this issue. We will post an update here when it has reached general availability.

**Comment by soarb** [comment]
@sarahkoop @danielebart  I can confirm that this still appears to be in issue with drop-in:6.2.0.

This is in our Sandbox environment with test cards: 4000000000001091 and 4000000000001109. Seemingly anything that actually triggers the 3DS Flow. 

On entering the OTP code in the challenge UI, once the browser switch returns to our App, I can see in our logs the expected liability shifted and possible flags are correct, based on the test card's scenario as described [here](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live)

We're able to mitigate this, as the first successful lookup and verification is returned to our App and we don't process the duplicate, which causes the "nonce is already consumed" error to be logged in the background.

Can anyone please confirm that there's a fix for this?

**Comment by soarb** [comment]
Also the same occurs when choosing Google Pay as the payment method (for a non network tokenized card). 

Again, I only take the first response as all associated Activities (should!) have been disposed of, so the second call doesn't make it back to my App

In this case the second lookup which gets triggered (I honestly have no idea how!) and subsequently handed off to the ThreeDSecureClient's continuePerformVerification method results in the following error:-

```
{"error":{"message":"Record not found"},"fieldErrors":[]}
```

Whereas the first call works fine.

**Comment by jaxdesmarais** [comment]
The Drop-in SDK is now in an [inactive status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories). Starting September 1, 2026 the Drop-in SDK will move to a [deprecated status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and we will no longer make any updates to this SDK. Processing will be supported for 1 year after the deprecation date, but you should upgrade immediately to avoid any disruption.

Starting September 1, 2027 the Drop-in SDK will move to an [unsupported status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and will no longer supported by Braintree developers or Braintree Support. Processing for unsupported SDKs can be suspended at any time.

Please migrate to the [Braintree SDK](https://github.com/braintree/braintree_android) to continue processing and receiving updates.
